import { BookCourse } from './types';

export const lettingGoCourse: BookCourse = {
  id: 'letting_go',
  titleAr: 'السماح بالرحيل: الطريق نحو التسليم',
  titleEn: 'Letting Go: The Pathway of Surrender',
  authorAr: 'د. ديفيد ر. هاوكينز',
  authorEn: 'Dr. David R. Hawkins',
  coverImage: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&w=400&q=80',
  descriptionAr: 'الدليل الهادف المتين لتفكيك الأنا وتحرير مشاعر القلق والغضب والتعلق، وبلوغ طاقات الشجاعة والسلام وسكينة الروح المطلقة وعلاج الجسد والروح.',
  descriptionEn: 'An advanced manual for dissolving emotional blockages, purifying anger, anxiety, and desire, and shifting safely to the energies of Courage, Love, and Peace.',
  isLocked: false,
  chapters: [
    {
      id: 'lg_ch1',
      chapterNum: 1,
      titleAr: 'الفصل الأول: آلية السماح بالرحيل وتحرير المشاعر المترسبة',
      titleEn: 'Chapter 1: The Letting Go Mechanism & Silent Emotional Release',
      descriptionAr: 'فهم علمي وعملي لكيفية تراكم الانفعالات والمشاعر الدفينة، والآلية الفعالة لقطع نزيف التوتر واسترداد الوعي الحاضر.',
      descriptionEn: 'An academic and practical decoding of emotional buildup, and Dr. Hawkins\' core surrender strategy to suppress cognitive exhaustion.',
      lessons: [
        {
          id: 'lg_ch1_l1',
          idNum: 1,
          titleAr: '1. شفرة كبت المشاعر: كيف تتراكم الأثقال الكامنة؟',
          titleEn: '1. Defining Emotional Compression: Behind Chronic Stress',
          duration: '4m',
          type: 'intro',
          contentAr: `يتعلم الفرد منذ طفولته المبكرة كيف يكتم انفعالاته وعواطفه السلبية هرباً من النقد الاجتماعي، مما يؤدي لتراكم **مجموعة ضليعة من التوترات الدفينة (Emotional Suppression)**.
          
**أنواع التعامل غير الصحي مع المشاعر:**
1. **الكبت والطمس (Suppression & Repression):** دفن الشعور بالكامل في غياهب اللاوعي.
2. **التفريغ والتنفيس (Expression):** إطلاق الشعور بصوت عار ومقاومة مفرطة، مما يبدد طاقة المحيط ويعمق الأزمة.
3. **الهروب والتشتيت (Escape):** اللجوء للملهيات والمخدرات والتلفيق الحسي لتجنب مواجهة الوعاء الداخلي.`,
          contentEn: `From early childhood, individuals accumulate high levels of negative energy through **Emotional Suppression**. Avoidance of discomfort formats a circular loop of constant neural dread and workplace exhaustion.
          
Observe the non-healthy mechanics of releasing feelings:
1. **Suppression & Repression:** Forcing the chronic anxiety into the subconscious container.
2. **Expression:** Vocalizing anger and rage, which merely spreads the negative current to peers.
3. **Escape:** Evading the inward state through synthetic distractions or endless television watching.`
        },
        {
          id: 'lg_ch1_l2',
          idNum: 2,
          titleAr: '2. شفرة وسحر الاستسلام: إنهاء المقاومة والاعتراف باللحظة',
          titleEn: '2. The Grace of Surrender: Turning off Internal Friction',
          duration: '3m',
          type: 'core',
          contentAr: `جوهر آلية **السماح بالرحيل (Letting Go)** يكمن في مراقبة حقيقة المشاعر دون المقاومة أو الرغبة في تغييرها أو الحكم عليها.

**خطوات السماح بالرحيل الأساسية:**
- اترك الشعور بسلام والفت انتباهك للطاقة الكامنة خلفه في جسدك.
- لا تحاول تحليل الأفكار المصاحبة； بل انظر إليها كغبار تافه يذوب تدريجياً.
- ثق أن الشعور كمسار من الضباب، سيعبر بانتظام إذا منحته حرية الحضور والرحيل بلا ردع.`,
          contentEn: `The core core of Dr. David Hawkins\' **Letting Go** strategy is to witness your inward sensation without any cognitive efforts to modify, alter, or judge it.

**The Golden Steps of Conscious Release:**
- Focus entirely on the physical raw energy inside your chest or belly, refusing to run from the pain.
- Ignore the circular theories or labels generated by the anxious mind.
- Maintain a position of peaceful observation until the heavy cloud of the negative current subsides naturally.`
        },
        {
          id: 'lg_ch1_l3',
          idNum: 3,
          titleAr: '3. تطبيقات وتمرين الحضور والتسليم المهني اليومي',
          titleEn: '3. Standard Tips: Embedding Surrender into Daily Labor',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لترسيخ عهد التسليم الواعي والتحرر المبرهن اليوم:
          
- **تطبيق \'مراقب الضغط المهني\':** عند رصد بوادر انفعال أو غضب من بريد إلكتروني حاد اليوم، توقف فوراً، ولا ترسل أي رد فوري； خذ دقيقة بمراقبة دقات قلبك الشاملة ودع غبار الضجر يتحرك ويرحل عن كاهلك بأمان.
- **تأمل تحرير الأثقال قبل النوم:** اختم يومك باستعراض مشاعرك وتفنيد شحن المقاومة وإطلاق سراح العالق، لترتقي بروحك وبدنك لأمان الفكر الكوني المميز الحكيم.`,
          contentEn: `Practical steps to utilize in the office today:
          
- **The Email Resister Pause:** When receiving a provoking corporate memo, stay silent. Direct 100% of your attention to the warm tightness in your chest. Breathe cleanly and allow the initial chemical wave to melt before executing any verbal action.
- **The Nightly Clearing Scan:** Before rest, observe any residual disputes. Concede defeat to the static past and cleanly release your claim to past arguments.`
        }
      ],
      quiz: [
        {
          questionAr: "ما هو الجوهر الفعلي الصارم لآلية 'السماح بالرحيل' لدى د. ديفيد هاوكينز؟",
          questionEn: "What is the primary action required during the Letting Go process?",
          optionsAr: [
            "محاربة الأفكار وكتابة خطط تحليلة مبرهنة لقمعها بالقوة ومناقشة الخصوم.",
            "مراقبة طاقة وملمس الشعور في الجسم بحضور غامر والتحرر من الرغبة في مقاومته أو التهرب منه، دون تتبع للأفكار الجانبية المصاحبة له بالكلية.",
            "تفريغ شحنة الغضب العشوائية بوجوه الزملاء لحماية مناعتك الجسدية."
          ],
          optionsEn: [
            "Aggressively debating your enemies and drafting logical scripts to suppress the thoughts.",
            "Quietly observing the raw physical energy of the sensation in your form, while surrendering all efforts to resist, alter, or evaluate it.",
            "Screaming at your colleagues immediately to keep your system safe from heart strains."
          ],
          correctIndex: 1,
          explanationAr: "السماح بالرحيل يبدأ من الشعور الجسدي لا الدوامات الفكرية الروتينية الزائفة، والمراقبة تصون حضورك وتفكك الشحنة بأسرع وقت.",
          explanationEn: "Releasing targets the physical container of feeling, not the frantic interpretations of thoughts. This immediately drains the negative cloud of power."
        }
      ]
    },
    {
      id: 'lg_ch2',
      chapterNum: 2,
      titleAr: 'الفصل الثاني: تشريح العواطف وخريطة هرم وعي هاوكينز المعياري',
      titleEn: 'Chapter 2: Anatomy of Emotions & Hawkins’ Scale of Consciousness',
      descriptionAr: 'تحليل دقيق لخريطة مستويات الوعي الإنساني، وقدرة ترددات الطاقة على جذب أو طرد النجاح والسكينة.',
      descriptionEn: 'A precise breakdown of the Map of Consciousness, showing how energy vibrations determine failure or prosperity at work.',
      lessons: [
        {
          id: 'lg_ch2_l1',
          idNum: 1,
          titleAr: '1. لغز خريطة الوعي: من العار إلى السلام',
          titleEn: '1. Deciphering the Map of Consciousness: Ground Zero to Enlightenment',
          duration: '4m',
          type: 'intro',
          contentAr: `وضع هاوكينز **مقياساً ثورياً لمعايرة مستويات الوعي البشري (Map of Consciousness)** يمتد من الرقم ١ حتى ١٠٠٠.
          
**المنعطف الإستراتيجي الأكبر في المقياس:**
- **المستوى ٢٠٠ (الشجاعة - Courage):** هو عتبة العبور من الطاقة السلبية الهدامة إلى القوة البناءة والنزاهة والصدق.
- **تحت ٢٠٠:** مشاعر الضعف كالخوف والأسى واللامبالاة والغضب والفخر. هذه الترددات تعطل خلايا الدماغ وتفقدك الفاعلية الإنتاجية والوقار الأكاديمي.
- **فوق ٢٠٠:** مشاعر القوة كالحياد والاستعداد والقبول والحب والسلام.`,
          contentEn: `Dr. Hawkins structured a **Map of Consciousness** scale calibrating human states on logarithmic tiers from 1 to 1000.
          
**The ultimate critical pivot point:**
- **Level 200 (Courage):** This is the ultimate crossing border from destructive frequencies into constructive, objective, and integer currents of power.
- **Below level 200:** Sufferings like Fear, Grief, Apathy, and Arrogance. These currents drain resource and generate cellular friction.
- **Above level 200:** Authentic capabilities like Neutrality, Willingness, Acceptance, and Intellectual Love.`
        },
        {
          id: 'lg_ch2_l2',
          idNum: 2,
          titleAr: '2. ترددات الفشل مقابل طاقة الوفرة المبرهنة',
          titleEn: '2. Relational Vibrations: Discerning Soporific and Vibrant Currents',
          duration: '3m',
          type: 'core',
          contentAr: `عمل خلايا دماغك وجسدك بانتظام كجهاز إرسال واستقبال ذبذبي دائم.
          
**الذبذبات الشقية (Low Frequencies):**
- حين تجلس في تردد الغضب (١٥٠) أو الفخر (١٧٥) بالعمل، ينفر منك الأخرون وتجد تعقيدات روتينية وسوء فهم مستمر في صفقاتك وعقودك اليومية.
          
**الذبذبات البهية (High Frequencies):**
- حين تكون في مستوى القبول (٣٥٠) أو العقل (٤٠٠)، تنزاح المشاكل تلقائياً وتحوز قبولاً باهراً وإقبالاً عجيباً من الأكفاء لحل القضايا الصعبة وتسييس الثروة والمعرفة بوقار.`,
          contentEn: `Your physical system serves as a live transmitter and receiver of conscious frequency:
          
**Soporific Currents (Below 200):**
- When dwelling in Anger (150) or Pride (175), your commercial contracts and social connections experience ongoing friction and complex strategic misunderstandings.
          
**Vibrant Currents (Above 200):**
- Anchored in Acceptance (350) or Reason (400), complex office issues resolve organically. High-value opportunities migrate to your desk as you radiate profound security and academic authority.`
        },
        {
          id: 'lg_ch2_l3',
          idNum: 3,
          titleAr: '3. ممارسات القفز اللحظي للتردد السليم الصالح',
          titleEn: '3. Standard Tips: Shifting Your Internal Scale in Real Time',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك خطة الارتقاء الذبذبي السريع اليوم:
          
- **تطبيق \'التحقق الوجاري\':** ثلاث مرات باليوم، حدد ترددك الحالي على الخريطة: هل أنت تحت الشجاعة (٢٠٠)؟ إذاً توقف، تنفس بعمق، إعترف بالشعور ووجه نيتك للتسليم بسلام وقار.
- **تأمل تذويب المقاومة لرفع الهالة:** دع الأفكار الهاربة تذهب واسمح للهالة الحيوية لجسدك الداخلي بالانبثاق للتسامي التام والجمال المعرفي المشرق.`,
          contentEn: `Execute these swift shifts to elevate your daily scale today:
          
- **The Internal Calibration Check:** Three times daily, define your emotional coordinate. Are you below level 200? Release your entitlement to grievance and direct your state to neutral acceptance.
- **The Core-Vibration Lift:** Surrender the urge to battle external elements. Reconnect with inward stillness to elevate your functional authority and recharge your cellular integrity.`
        }
      ],
      quiz: [
        {
          questionAr: "ما هي العتبة الدقيقة التي تفصل بين ترددات الوعي المدمرة والوعي البناء في هرم هاوكينز؟",
          questionEn: "What is the critical boundary dividing negative and positive states on Hawkins’ scale?",
          optionsAr: [
            "مستوى اللامبالاة المطلقة عند تردد ٥٠.",
            "مستوى الشجاعة (٢٠٠ - Courage)، والذي يمثل الانتقال من الضعف الهدام إلى الفاعلية والقوة والنزاهة الواعية.",
            "مستوى الشهرة والرياء التفاخري الفاضح عند مستوى ٩٥٠."
          ],
          optionsEn: [
            "The level of absolute Apathy at calibration 50.",
            "Level 200 (Courage), denoting the vital passage from draining weakness into objective, constructive empowerment.",
            "The level of boastful vanity and false display at calibration 950."
          ],
          correctIndex: 1,
          explanationAr: "الشجاعة (٢٠٠) هي منعطف الصدق والأمان، والارتقاء فوقها يعصم الفرد من ضياع الطاقة وسوء الإدارة.",
          explanationEn: "Courage (200) serves as the energetic fulcrum. Reaching it guards you against critical output drain and interpersonal toxicity."
        }
      ]
    },
    {
      id: 'lg_ch3',
      chapterNum: 3,
      titleAr: 'الفصل الثالث: كسر جمود اللامبالاة والكتئاب (بوابة الوعي الحركي)',
      titleEn: 'Chapter 3: Shattering Apathy & Depression: Igniting Active Focus',
      descriptionAr: 'تفكيك طاقة التبلد والفتور، والتخلص من عقلية الضحية للاندماج مجدداً بسلام وإنجاز عريض.',
      descriptionEn: 'Deconstructing helplessness and static grief, and releasing the victim mentality to restore high motivation and output.',
      lessons: [
        {
          id: 'lg_ch3_l1',
          idNum: 1,
          titleAr: '1. تشريح هاوية الفتور: وهم \"لا فائدة\" العجيب',
          titleEn: '1. The Anatomy of Static Apathy: Relinquishing the Victim Role',
          duration: '4m',
          type: 'intro',
          contentAr: `تعتبر **اللامبالاة (Apathy)** والتبلد من أخطر ترددات الوعي المنخفضة (٧٥)، حيث يبدو الوجود مظلماً ومملاً، وينهمر العقل في تكرار عبارات الهزيمة والتباكي.
          
**سجن عقلية الضحية:**
- في هذا التردد، يرفض الشخص المبادرة مدعياً أن الظروف والشركاء والبنوك تآمروا ضده، مما يعطل فاعليته بالكامل. الحقيقة الصارمة أن هذا التردد هو حالة كسل وحيلة دفاعية للأنا لتتفادى مشقة العمل والشجاعة.`,
          contentEn: `**Apathy** calibrates at a low frequency of 50. It acts as a cognitive fog where your intellect declares: "I decline to try, there is no hope anyway."
          
**The Victimhood Prison:**
- In this loop, the subject attributes all failures to external forces—such as the economy, strategic policies, or toxic management. In reality, Apathy is an ego defense mechanism intended to evade the necessary risks and labor of Courage.`
        },
        {
          id: 'lg_ch3_l2',
          idNum: 2,
          titleAr: '2. تفكيك الشلل الحركي: الخروج من ثقب اليأس الأسود بوعي',
          titleEn: '2. The Ignition Protocol: Injecting Life back into the Engine',
          duration: '3m',
          type: 'core',
          contentAr: `لكي تخرج من التبلد، لا تطالب نفسك بسلام فجائي； بل اعترف بوجود اليأس واسمح بالرحيل لشحنة المقاومة العالقة في عضلاتك وعمودك الفقري.
          
**الحصانة الدماغية المستردة:**
- رصد الرغبة الدفينة بالانعزال والهروب ومواجهتها بصمت.
- اتخذ خطوة عملية صغيرة للغاية اليوم بلا ترقب عاطفي للنتائج الرائعة، فالحركة تدمر ركود الخوف والبلادة تلقائياً.`,
          contentEn: `To break free from depression and stagnation, do not demand immediate bliss. Acknowledge your inner numbness and witness the dense current in your spine.
          
**Restoring mental motion:**
- Observe your subconscious urge to sleep excessively or run away from duties.
- Take one microscopic, practical step today without waiting for magnificent emotional rewards. Motion physically shatters the chemical inertia of apathy.`
        },
        {
          id: 'lg_ch3_l3',
          idNum: 3,
          titleAr: '3. تطبيقات اليوم: صيانة النفس ضد الاستسلام الاجتماعي والتبلد',
          titleEn: '3. Standard Tips: Practical Rituals to Bypass Mental Stagnation',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لإبعاد شبح التبلد المهني اليوم:
          
- **تطبيق \'التحرك العضلي الدقيق\':** رتب مكتبك لـ١٠ دقائق أو قم بإنجاز تفصيلي تافه مؤجل； الحركة تفرغ الشلل الذهني وتعيد تشغيل المناعة بانتظام.
- **تأمل الاستبصار الشجاع:** اقطع نقاش الأنانية وضع نية طاهرة للهداية والعمل بنشاط وقوة لتجاوز الأكاذيب الذهنية المبررة للكسل والخنوع.`,
          contentEn: `Apply these practices to prevent professional numbing today:
          
- **The 10-Minute Spatial Cleanse:** Organize your physically immediate surroundings or resolve one long-delayed trivial email. Small successes disrupt the passive feedback loop in your brain.
- **The Intentional Spark:** Declare to your system: "I yield my preference to remain helpless. I choose to introduce active attention directly to my task Now."`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يساهم السماح بالرحيل في تفكيك جمود اللامبالاة والفتور الإداري؟",
          questionEn: "How does the surrender workflow assist in dissolving career apathy?",
          optionsAr: [
            "بالاعتراف الواعي بالفتور مع السماح برحيل طاقة المقاومة المتكلسة بالبدن، والبدء بالحركة الفيزيائية عبر خطوات عملية دقيقة دون انتظار لنتائج مبهرة فورية.",
            "عبر إلقاء الملامة على السياسات وتوفير مبررات فلسفية للبقاء في السرير لتجنب الأعباء.",
            "بالمطالبة بقروض إضافية وصرف المبالغ على الملهيات للتشتيت الحسي."
          ],
          optionsEn: [
            "By consciously identifying the inner numbness, relinquishing somatic resistance, and executing microscopic physical tasks without placing demands on swift validation.",
            "By blaming management strategies and constructing eloquent intellectual stories to rationalize remaining in bed.",
            "By requesting infinite financial loans and exhausting assets on massive physical escapes."
          ],
          correctIndex: 0,
          explanationAr: "السماح بالرحيل يحولك من موقف الضحية المستسلمة إلى الفاعل الشجاع القادر على تسييس الطاقة بسلام وحكمة.",
          explanationEn: "Conscious release shifts your system from a passive defensive posture to an active baseline of complete ownership and mental clarity."
        }
      ]
    },
    {
      id: 'lg_ch4',
      chapterNum: 4,
      titleAr: 'الفصل الرابع: تذويب الأسى والحزن وعقلية الفقد الشقي',
      titleEn: 'Chapter 4: Transcending Grief & Releasing Somatic Sadness',
      descriptionAr: 'تطهير النفس من جراح الفقد وصدمات الأمس العالق، والتحول الشهم من البكاء والتعلق إلى الوفرة الروحية الصالحة.',
      descriptionEn: 'Purifying historical trauma, releasing anxious sorrow, and evolving gracefully from attachment to infinite spiritual abundance.',
      lessons: [
        {
          id: 'lg_ch4_l1',
          idNum: 1,
          titleAr: '1. تشريح الأسى: عندما يعلق العقل في تفاصيل الأمس الذاهل',
          titleEn: '1. The Somatic Trap of Grief: Behind Chronic Regret',
          duration: '4m',
          type: 'intro',
          contentAr: `يعاير **الأسى والحزن (Grief)** عند تردد ٧٥، وهو مستوى من الطاقة الوهنة يمتص فاعلية الدماغ ويجعل الشخص يشحب حزناً على ممتلكات أو أقران أو فرص ضاعت بالأمس.
          
**التعلق المرضي بوهم المصدر الخارجي:**
- ينبثق الأسى من وهم عقلي بأن مصدر سعادتك وأمانك كان شيئاً خارجياً تفردت به وفقدته； والحقيقة الصادمة أن المصدر الحقيقي للوفرة والسكينة يفيض من روح كينونتك الأصلية الحاضرة الآن، ولا يمكن لأحد سلبها منك.`,
          contentEn: `**Grief** calibrates in the heavy low-energy field of 75. Dwelling in this zone keeps your cognitive resources locked inside past failures and expired partnerships.
          
**The Attachment Trap:**
- Sadness is rooted in the mental illusion that your source of comfort or happiness was located entirely in an external object. When that object departs, the ego collapses into circular cycles of chronic regret.`
        },
        {
          id: 'lg_ch4_l2',
          idNum: 2,
          titleAr: '2. ذوبان دموع الأمس: كيف تفرغ طاقة الوجع من صدرك؟',
          titleEn: '2. Dissolving Nostalgic Sorrows: Turning Pain into Grace',
          duration: '3m',
          type: 'core',
          contentAr: `يعلمنا د. هاوكينز كيف أن دموع الأسى المترسبة تحتاج لوعي هادئ يتلقى الغصة في الحلق والصدر دون الحكم عليها بالسوء أو الهلع.
          
**خطوات الغسيل العاطفي والتطهير:**
- تنفس بانتظام، تلمس طاقة الضجر والوجع وافسح لها المجال لتكتمل وترحل بوقار； ثق أن الألم ما هو إلا تجربة كيميائية تعبر جسدك المادية لتتطهر روحك بالكلية وتعلق بأمان وعزيمة الحكماء الأكاديميين الأحرار.`,
          contentEn: `Dr. Hawkins clarifies that somatic grief must be greeted with high quiet presence that tracks the tightness in your throat and core without avoiding the sensory pain.
          
**The Process of Somatic Cleansing:**
- Breathe cleanly. Observe the sorrowful sensation like a storm passing through. Do not analyze why you are suffering； simply allow the feeling to exhaust its current, stripping the chronic memory of its toxic hold over your nervous system.`
        },
        {
          id: 'lg_ch4_l3',
          idNum: 3,
          titleAr: '3. ممارسات واسترجاع الحضور الصامد: التحرر من عقدة الفقد',
          titleEn: '3. Standard Tips: Releasing Attachment and Moving Forward Today',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لترسيخ عهد السكينة والصبر الشهم المحتسب اليوم:
          
- **تمرين \'التصالح الإستراتيجي مع الأمس\':** قل لنفسك بثبات وقار: "لقد حدث ذلك، الماضي صفحة مغلقة. لا يمكنني تغيير العقد الماضي. ماذا سأفعل بنبالة وشرف الآن؟".
- **تأمل شكر المحن لتفعيل الوفرة:** انظر للضربات الجائرة كمحفزات فولاذية صقلت شرفك وعزيمتك، وانطلق بساحات العمل تملأ الدنيا حضوراً وإنجازاً باذخاً مبرهناً.`,
          contentEn: `Utilize these practices to secure your composure today:
          
- **The Historical Non-Resistance Rule:** Repeat internally with poise: "What happened is done. I surrender the claim to alter the past. I cleanly redirect my mental focus to my current targets."
- **The Hardship Gratitude Frame:** Shift your perception of historic failures. Reframe them as demanding catalysts that forged your resilience and elevated your executive capacity.`
        }
      ],
      quiz: [
        {
          questionAr: "ما هو المصدر الحقيقي للسعادة وسكينة الروح الكبرى وفق ديفيد هاوكينز في آلية السماح بالرحيل؟",
          questionEn: "What is the authentic source of joy and security according to Hawkins?",
          optionsAr: [
            "المظاهر الخارجية والتملك الشره وصعود ممتلكات مادية تفاخرية زائفة بالكلية.",
            "قوة الكينونة والحضور بداخل روحك، وهي طاقة داخلية فياضة لا يمكن لعقود الماضي أو حوادث الأمس سلبها أو حجبها إذا ساد وعيك.",
            "البقاء في دوامة الأسى وتبرير عدم الإنتاجية بالحزن."
          ],
          optionsEn: [
            "External statuses, relentless accumulation, and climbing vanity tiers.",
            "The internal presence and energy of Being, which is an infinite source of joy that cannot be removed by past events or future uncertainties.",
            "Dwelling in historical sorrow and rationalizing your administrative failure."
          ],
          correctIndex: 1,
          explanationAr: "الاتصال بكينونتك الحية وسكينة الروح ينهي التردد الهش للأسى ويمنحك هيبة ويقين القادة الموثوقين بالكلية.",
          explanationEn: "Connecting to your inward STILLNESS neutralizes the painful frequencies of grief, installing unshakeable clarity and complete stability."
        }
      ]
    },
    {
      id: 'lg_ch5',
      chapterNum: 5,
      titleAr: 'الفصل الخامس: التغلب على الخوف وهلوسة القلق المعيق',
      titleEn: 'Chapter 5: Conquering Fear & Healing Chronic Cognitive Anxiety',
      descriptionAr: 'تفكيك عقد الرعب والفزع الاجتماعي، وتطهير النفس من וساوس التشتت، والصعود بثقة واقتدار لعقد صفقاتك ببراعة.',
      descriptionEn: 'Deconstructing panic, dissolving social anxiety and worry, and building an ironclad presence for executive functions.',
      lessons: [
        {
          id: 'lg_ch5_l1',
          idNum: 1,
          titleAr: '1. سيكولوجيا الخوف الوهن: مخدر الهمة وحاضنة التردد',
          titleEn: '1. The Somatic Grip of Fear: The Ultimate Mind Constraint',
          duration: '4m',
          type: 'intro',
          contentAr: `يعاير **الخوف (Fear)** عند تردد ١٠٠، وهو مستوى متدني من الطاقة يتسيد ساحات عمل الكثيرين، جاعلاً إياهم مقيدين بجدران الخوف من الفشل، أو كره التغيير، أو الهلع من المرض والمستقبل الوهمي.
          
**عرقلة طاقة اتخاذ القرار:**
- يعمل الخوف كحاجز نفسي سميك يشل فكر الفرد ومبادرته، ويحيد به بعيداً عن بر النجاح； فالخوف يخلق في عقلك ملايين الاحتمالات الهزلية الخائبة ليقنعك بالبقاء في حدود منطقتك الضيقة خشية النقد أو المجازفة الشجاعة الصالحة.`,
          contentEn: `**Fear** calibrates at 100. It is a powerful mental constraint that locks individuals inside standard routines, dreading failure, rejecting organizational shifts, or obsessing over imaginary futures.
          
**Administrative Paralysis:**
- Worry functions like a thick energetic wall that suppresses initiative and compromises decision-making. Your mind invents catastrophic complications to justify withdrawing from critical risks or major professional expansion.`
        },
        {
          id: 'lg_ch5_l2',
          idNum: 2,
          titleAr: '2. تفكيك وهن القلق: كيف تواجه التحدث أمام الجمهور بثقة حديدية؟',
          titleEn: '2. Overriding Social Anxiety: The Public Speaking Protocol',
          duration: '3m',
          type: 'core',
          contentAr: `للتخلص من الخوف، تنفس بعمق وتتبع تشنج العضلات والبرودة بأطرافك وجسدك بصمت تام بلا هلع.
          
**استراتيجية التطهير الاجتماعي هاوكنز:**
- عند دعوتك للحديث أمام جمع مهاري أكاديمي مهيب، اعترف بخجلك ورهبتك وصوب تفكيرك وجسد وعيك بالكامل للشعور بتيار الحياة ببدنك.
- تجاهل السيناريوهات الدماغية الغبية； فركز بنسبة ٩٠٪ بحضورك الداخلي والصفاء ليشرق حديثك وتفيض حكمتك بوقار يبهر الحاضرين.`,
          contentEn: `To dissolve worry, study the physical somatic tension (such as hand coolness or shallow breathing) with quiet objective precision.
          
**The Public Speaking Protocol:**
- When presenting to a large corporate board, observe the initial spike of panic in your gut. Keep your awareness anchored there, ignoring thoughts about getting rejected.
- Direct 90% of your energy to the somatic physical sensations. The panic is simply energy； when non-resisted, it converts into charisma and authentic authority.`
        },
        {
          id: 'lg_ch5_l3',
          idNum: 3,
          titleAr: '3. ممارسات واسترداد الثقة: تمرين الوعاء السلمي اليومي',
          titleEn: '3. Standard Tips: Releasing Worry in Your Daily Operations',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لإبعاد القلق واسترجاع السلام الصامد والسيادة الكلية اليوم:
          
- **تطبيق \'التحويل الترددي الفوري\':** كلما شعرت بوسواس الخوف، ردد بثبات: "إنها فكرة وليست حقيقة. أنا أسمح بالرحيل لشحنة الذعر، وأختار الحضور والشجاعة الآن".
- **تأمل الحصانة الذهنية الصامتة:** تنفس ببطء محتفظاً بقداسة حضورك ونظافتك المعرفية التامة ضد لغو الهلع وسفسطات الخائفين من الغد الوهمي.`,
          contentEn: `Construct an ironclad baseline using these daily steps:
          
- **The Cognitive Disconnection Check:** When a projection of future ruin enters your thoughts, say: "This is a phantom movie, not current reality. I surrender this fear. I choose focused attention Now."
- **The Somatic Shielding Ritual:** Deeply scan your form hourly. Release somatic knots of tension in your neck or core to secure complete intellectual immunity against outer hysteria.`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يفيد تمرين الاتصال بالجسد وتذويب الخوف في التفريط بتبعات الذعر والقلق الإداري؟",
          questionEn: "How does body awareness and fear release support us during corporate crises?",
          optionsAr: [
            "يؤدي لانطواء الموظف وهروبه من الأسواق وعجزه عن سداد المطالبات المالية المبرهنة.",
            "يحول برودة وقلق الجسم إلى حضور هادئ وقار، يطرد ذهنياً التشتت والهلع ويمنحك شجاعة ووضوحاً وثباتاً لاتخاذ قرارات ناضجة جريئة بذكاء واقتدار.",
            "يجعلك تعادي رؤساءك وتتباكى في الاجتماعات الهامة للحصول على تلميع تفاخري زائف."
          ],
          optionsEn: [
            "It forces you to isolate yourself from commercial markets and skip basic fiscal duties.",
            "It converts the initial spike of physical dread into focused presence, clearing hyper-reactive panic and arming you with complete composure for swift decision-making.",
            "It prompts you to challenge senior leaders and weep during major briefings to gain basic pity."
          ],
          correctIndex: 1,
          explanationAr: "الاتصال الصامت بالجسد ينزع فتيل الخوف الكيميائي بالبدن لتتصرف من موقع الشجاعة والقوة الأكاديمية المطلقة.",
          explanationEn: "Integrating body awareness disarms the biological panic, returning your system seamlessly to Courage and absolute executive competence."
        }
      ]
    },
    {
      id: 'lg_ch6',
      chapterNum: 6,
      titleAr: 'الفصل السادس: تذويب الرغبة والتعلق والملكية الشرهة الشقية',
      titleEn: 'Chapter 6: Dissolving Desire & Releasing Chronic Attachment',
      descriptionAr: 'تطهير النفس من وهم الركض المتواصل وراء المظاهرات، والتحول الشجاع من التعلق والشهوة الشقية إلى الوفرة الروحية الصالحة.',
      descriptionEn: 'Transcending obsessive craving and the chasing treadmill, and evolving to clean, peaceful intent and abundant manifestation.',
      lessons: [
        {
          id: 'lg_ch6_l1',
          idNum: 1,
          titleAr: '1. سيكولوجيا الرغبة والشهوة: ترنحة الجري بلا توقف',
          titleEn: '1. The Myth of Craving: Breaking the Obsessive Wanting Treadmill',
          duration: '4m',
          type: 'intro',
          contentAr: `تعاير **الرغبة (Desire)** عند تردد ١٢٥، وهو مستوى من ذبذبات الطاقة يبدو في فلك المعاصرين كإنجاز； بينما في الحقيقة هو طاقة ملحة نهمة تسعى باستمرار لامتلاك الأصول والممتلكات طمعاً في ملء فجوة نقص داخلي عميق.
          
**لغز التسويف والركض الدائم وبطء الحصاد:**
- يردد عقل الرغبة الشقية عبارة: "لن أكون سعيداً ومكتفياً حتى أحصل على هذه السيارة، أو هذه الترقية، أو هذا المنصب التفاخري". هذا التثبيت المفرط على الغنائم والتعلق بها يقود الموظف لتشتت دائم ويشحنه بقلق شديد خشية ضياع الفريسة.`,
          contentEn: `**Desire** calibrates at 125. While modern corporate cultures reward constant hunger, Hawkins labels it as a baseline of chronic lack—a constant frantic state of chasing external trophies to fill a deep inward void.
          
**The Treadmill Paradox:**
- The wanting mind states: "I will remain miserable until I secure this promotion or buy this vehicle." This attachment creates severe performance anxiety and chronic focus issues, delaying actual objective success.`
        },
        {
          id: 'lg_ch6_l2',
          idNum: 2,
          titleAr: '2. تحويل الرغبة الشقية إلى نية صلبة منجزة بسلام وقار',
          titleEn: '2. From Obsession to Execution: Aligning Intention with Stillness',
          duration: '3m',
          type: 'core',
          contentAr: `يعلمنا ديفيد وبكار كيف أن الفرق شاسع بين الرغبة الملتهبة وبين **النية الصهباء المنجزة بوضوح وصمت (Clear Intent)**.

**كيف تتخلص من التعلق وتكسب صفقاتك ببراعة؟**
- توقف عن الركض المتوتر خلف المكسب المالي； اعترف برغبتك الشرهة واسمح لها بالرحيل بوعي. عندما يتلاشى التعلق والشغف المقلق، يرتد تيار ذكائك ويفاض بحكمة، لتتحقق أهدافك بصمت وسهولة باذخة دون بذل جهود عشوائية خائبة.`,
          contentEn: `Dr. Hawkins distinguishes between hyper-reactive desire and **Clean Intention**. 

**Navigating business without attachment:**
- Release the nervous dread of not getting the contract. Accept your frantic craving and witness it inside your form until the energetic grip loosens. Once you surrender attachment to the outcome, you act from a position of absolute power, allowing outcomes to arrange themselves naturally.`
        },
        {
          id: 'lg_ch6_l3',
          idNum: 3,
          titleAr: '3. ممارسات واستشفاء الوفرة: تطبيقات عملية اليوم لتحقيق الحرية',
          titleEn: '3. Standard Tips: Releasing Chasing Mindsets and Mastering focus',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه التطبيقات لقطع دابر الاستحواذ والتعلق المظهري بالعمل اليوم:
          
- **تطبيق \'التحرير الإستراتيجي للمطامع\':** قبل خوض تفاوض مهيب، اجلس بمفردك، تنفس بعمق ودع الرغبة الشديدة بالربط أو السيطرة تزول بسلام. ادخل الاجتماع حراً ومكتمل الأرجح بوقار الكينونة.
- **تأمل كفاية الشرف والوفرة الروحية:** انظر لخيراتك واستحوذ على الوفرة من باطن نفسك، مبرهناً للجميع وقارك وحكمة فكرك الصالح الساكن المميز.`,
          contentEn: `Practice these steps to release commercial desperation today:
          
- **The Pre-Negotiation Disengagement Prep:** Before a crucial negotiation, sit in absolute silence for 5 minutes. Release the obsessive need to win or manipulate. Enter the boardroom complete and grounded.
- **The Sufficiency Recalibration:** Direct your focus to your current intellectual and energetic assets. Cultivating internal satiety terminates status desperation and draws partners to your orbit.`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يفيدنا تحرير التعلق والسماح برحيل الرغبة الشرهة في الصفقات والمشاريع؟",
          questionEn: "How does releasing attachment and obsessive craving improve our career output?",
          optionsAr: [
            "يؤدي لتكاسل الفرد وعزوفه عن السعي المعرفي وعضويته بالشركات والمشاريع الكونية.",
            "يزيل القلق والتوتر الذي يعبر بوضوح عن الضعف والنقص، ويمنحك نية صلبة واضحة وحضوراً وقوراً يؤهلك للاتفاق والفوز بسهولة ودون تشتيت.",
            "يجعلك تتنافر مع زملائع وتعلن إفلاسك هرباً من النفقات الإدارية."
          ],
          optionsEn: [
            "It causes active laziness and stops you from studying or joining global projects.",
            "It resolves performance anxiety and scarcity mindsets, providing a clear intention and unshakeable poise that helps you secure terms with dignity.",
            "It forces you to feud with colleagues and declare bankruptcy to evade fiscal requirements."
          ],
          correctIndex: 1,
          explanationAr: "تسيير النوايا بصمت وهدوء يخلق وقار حضور كامل الحكمة يجذب الأكفاء لصفك، بينما الذعر والحرص يعطل النجاح.",
          explanationEn: "Aligning clean intention with unshakeable stillness builds deep trust with partners, whereas anxious desperation pushes success away."
        }
      ]
    },
    {
      id: 'lg_ch7',
      chapterNum: 7,
      titleAr: 'الفصل السابع: قيادة الغضب وإخماد ثوران الأحقاد والضغائن',
      titleEn: 'Chapter 7: Transcending Anger: Channeling Reactive Energy Productively',
      descriptionAr: 'تطهير الروح من الاستشاطة وسرعة الانفعال، والاستفادة البناءة من الاندفاع الهرموني لخدمة الأهداف الفولاذية النبيلة بسلام.',
      descriptionEn: 'Purifying reactive rage, overcoming historic grudges, and cleanly channeling high somatic adrenaline into focused risk management.',
      lessons: [
        {
          id: 'lg_ch7_l1',
          idNum: 1,
          titleAr: '1. سيكولوجيا الغضب الحامض: صمامات الانفجار وفخ ثوران الأنانية',
          titleEn: '1. The Somatic Heat of Rage: Behind Sudden Outbursts',
          duration: '4m',
          type: 'intro',
          contentAr: `يعاير **الغضب وثوران الانفعال (Anger)** عند تردد ١٥٠، وهو طاقة عاصفة حامية في الجسم والدم، تنبثق غالباً من إعاقة رغبة شديدة أو شعور بالتهديد لمصالح الأنانية الكاذبة.
          
**خطر الغضب الدائم على الروع والروح:**
- يحرق الغضب المستمر هدوء الموظف ومناعته، ويخلق في دوائر العمل احتقاناً روتينياً وخصومات حامية； فالغضب حيلة غريزية للأنا المتطرفة لتفرض وجوداً مزيفاً عبر الترهيب اللفظي والتصلب في الآراء بوقاحة.`,
          contentEn: `**Anger** calibrates in the turbulent energetic field of 150. This state of somatic heat is activated when an obsessive desire is blocked or when the ego feels threatened.
          
**Relational Destruction:**
- Prolonged rage compromises your cognitive bandwidth and damages your circulatory system. Outbursts destroy your professional authority and generate deep, reactive resistance inside your business partnerships.`
        },
        {
          id: 'lg_ch7_l2',
          idNum: 2,
          titleAr: '2. ترويض طوفان الاستشاطة: كيف تستثمر الغليان الذبذبي بوعي؟',
          titleEn: '2. The Adrenaline Conversion Rule: Channeling Raw Force cleanly',
          duration: '3m',
          type: 'core',
          contentAr: `يعلمنا تول وبكار وهوكنز أن طاقة الغضب الهرمونية هي وقود خارق للعادة إذا أحسن الوعي تلقيها وعزلها عن ردة الفعل الانفعالية.

**الاستثمار الإستراتيجي لقوة الغضب:**
- عند استشاطتك في اجتماع مشحون، لا تنفجر لفظياً ولا تكتم الضجر ببدنك； تجنب الطرفين.
- اشعر بحرارة الغليان بصدرك وذراعيك ودعها تتطهر وتستقر. وجه هذا الاندفاع الحركي الفولاذي لخدمة مبادراتك وتصميم مشاريع إستراتيجية هادفة بثبات وقار دون الإساءة للأخرين.`,
          contentEn: `Dr. Hawkins clarifies that the raw biological charge of anger is an potent fuel if isolated from reactive verbal actions.

**The Conversion Methodology:**
- During heated corporate dispute, stay completely silent. Choose neither to explode nor to suppress the somatic heat.
- Witness the thermal energy in your chest and arms. Allow the immediate chemical wave to resolve cleanly. Then, direct this intense current of focused energy directly into executing tasks and completing your deadlines.`
        },
        {
          id: 'lg_ch7_l3',
          idNum: 3,
          titleAr: '3. ممارسات فض النزاع الحاد وإشعال السماح السامي',
          titleEn: '3. Standard Tips: Transcending Grudges and Healing Workplace Grievance',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك خطة إخماد النزاعات المهنية المتوترة وعقد السماح السامي اليوم:
          
- **تطبيق \'صمام الإخماد المبرهن\':** عند استلام نقد جاف جائر، تذكر مقولة المسيح: "دع الأفكار الهدامة تذهب"، ولا تنهمر بتبادل الشتائم العبثية الخائبة； ترفع بوقار العارفين الصالحين.
- **تأمل تصفية الضغينة لراحة الخلايا:** اعف بوعي وبصمت تام عن خصومك في الأسواق والدوائر لتوفر طاقة خلاياك الذهنية للأهداف الكبرى والصدارة الفكرية.`,
          contentEn: `Apply these practices to maintain absolute poise today:
          
- **The Non-Reaction Buffer:** When receiving public criticism, maintain a calm, relaxed posture. Do not prepare dynamic verbal counter-attacks； remain entirely centered.
- **The Grudge-Clearing Release:** Consciously forgive corporate peers for past strategic errors. Releasing the right to collect grievances saves immense mental energy for high-level creative labor.`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يفيدنا تسيير طاقة الغضب والسماح برحيل ردات الفعل الانفعالية بالوظيفة؟",
          questionEn: "How does releasing reactive anger support us in long-term career growth?",
          optionsAr: [
            "يؤدي لتخدير فكر الفرد وهروبه من حركية الأسواق والمشاريع الكونية.",
            "يوجه ذبذبات الطاقة الحيوية الناتجة عن الغليان الكيميائي لخدمة خطط استثنائية طموحة بمبادراتك المهنية بصمت ووقار، دون الانجرار لمعارك جانبية عبثية تهدر وقار حضورك الصادق.",
            "يجعلك تطالب بفصل زملائك من العمل لعرقلة المنافسة بوقاحة وعنف."
          ],
          optionsEn: [
            "It paralyzes your drive and makes you flee global commercial activities.",
            "It channels the massive biochemical charge of anger directly into solving complex problems and executing strategic plans, completely bypassing toxic verbal conflicts.",
            "It forces you to demand the immediate firing of your colleagues to reduce competition with arrogance."
          ],
          correctIndex: 1,
          explanationAr: "إعادة توجيه طاقة الغضب بصمت يمنحك هيبة وحضوراً فولاذياً يفرض الصدارة العلمية والوقار الأكاديمي المميز.",
          explanationEn: "Somatic conversion of reactive energy installs profound executive authority, distinguishing you as an authentic, self-mastered professional."
        }
      ]
    },
    {
      id: 'lg_ch8',
      chapterNum: 8,
      titleAr: 'الفصل الثامن: الفخر وتجاوز فخاخ وهم العظمة والكبر الوهن',
      titleEn: 'Chapter 8: Releasing Intellectual Pride & False Ego Vulnerabilities',
      descriptionAr: 'تفكيك عقد الفخر المظهري والغرور Mتهكم، والارتقاء بالتواضع ومصداقية المعرفة الملتزمة الشاملة.',
      descriptionEn: 'Deconstructing scientific vanity and false pride, and shifting to genuine competence backed by empty-plate academic humility.',
      lessons: [
        {
          id: 'lg_ch8_l1',
          idNum: 1,
          titleAr: '1. سيكولوجيا الفخر: مظهر وهمي من الوقار الكاذب المتأرجح',
          titleEn: '1. The Fragility of Pride: The Elegant Mask of Subconscious Insecurity',
          duration: '4m',
          type: 'intro',
          contentAr: `يعاير **الفخر الكاذب والغرور (Pride)** عند تردد ١٧٥، وهو مستوى من ذبذبات الطاقة يتسرب لساحات ذوي الشهادات والمناصب العالية، جاعلاً إياهم يسيرون بتعجرف وتصلب معرفي مفرط.
          
**هوية الأهمية الزائفة والضعف الدفين الكامن:**
- الفخر هو مجرد غطاء من الطلاء الخارجي ترتديه الأنا المتهكمة لتتفادى مواجهة شعور عميق بالنقص أو الخوف من الانكشاف； فالغرور يجعل الشخص يرفض قراءة البيانات الجديدة وينهمر في تفنيد الخبراء بوقاحة لكي يري الجميع تفوق ركابه الخائبة بالدائرة.`,
          contentEn: `**Pride** calibrates in the energetic field of 175. It is a highly common state among highly credentialed professionals, manifesting as scientific rigidity, corporate arrogance, and intellectual snobbery.
          
**The Core Vulnerability:**
- Vanity is merely an elegant armor designed by the ego to conceal subconscious insecurity. The proud mind rejects new datasets and attacks peer reviews to enforce a false illusion of intellectual dominance.`
        },
        {
          id: 'lg_ch8_l2',
          idNum: 2,
          titleAr: '2. سحر التواضع المعرفي: فضيلة الكبار وبوابة التدفق السليم',
          titleEn: '2. The Pathway of True Humility: Shifting from Vanity to Pure Integrity',
          duration: '3m',
          type: 'core',
          contentAr: `يعلمنا بكار وهاوكينز أن التواضع الروحي والتبذل العلمي النقي هو السلاح الأقوى لمجابهة نبرات الفشل والبلادة بالعمل.

**كيف تتخلص من الكبر وتكسب محبة الجميع وأثواب الصدارة؟**
- اعترف برغبتك بالظهور والتفاخر والرياء المعرفي التافه； انظر إليها كطاقة مكبوثة واسمح لها بالرحيل. عندما يتلاشى الكبر وتتخل عن الحاجة للبرهنة الدائمة للأخرين بذكائك، تظهر بمظهر وقار الحكماء الحقيقيين وتحظ بالقبول الصادق لآرائك ببراعة.`,
          contentEn: `Evolving beyond intellectual vanity requires embracing the empty-plate posture of **Genuine Humility**.

**How to dissolve arrogance and build genuine authority:**
- Confront your subconscious urge to brag, show off credentials, or put down others during technical discussions. Witness and surrender this craving for self-glorification. Letting go of visual vanity installs complete academic poise and captures sincere respect.`
        },
        {
          id: 'lg_ch8_l3',
          idNum: 3,
          titleAr: '3. ممارسات تواضع العلماء: تطبيقات بساحات العمل اليوم',
          titleEn: '3. Standard Tips: Releasing egoic demands and Mastering focus Today',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لإبعاد شبح التعالي واسترداد التواضع المعرفي واليقين الحاد اليوم:
          
- **تطبيق \'الاعتراف الذكي بالقصور\':** في اجتماع مهاري معزز، حين يتم طرح مسألة لا علم لك بها، قل بسلام وقار: "لا علم لي بدقائق هذه المسألة، سأدرسها وأجيبكم بالبراهين". هذه الكلمات تبرز وقارك وثقتك التامة بنفسك.
- **تأمل ثناء الأقران لرفع الصفاء العضوي:** امتدح الزملاء بصدق وبدون لغو الرياء، ودع كفاءاتهم تنبثق ليرتفع الأمان التام ونقاء ساحة العمل الكونية بالكامل.`,
          contentEn: `Practice these steps to ensure complete intellectual integrity today:
          
- **The Poised "I Don\'t Know" Check:** When encountering an unfamiliar technical query in a briefing, state with relaxed confidence: "I decline to theorize on this dataset without studying it first. I will review it and return with the logical answers."
- **The Authentic Peer Acknowledgment:** Praise the analytical efforts of your colleagues without synthetic flattery. This neutralizes competition anxieties and cleans the creative current.`
        }
      ],
      quiz: [
        {
          questionAr: "ما هو المصدر الأساسي لهشاشة وضعف مستوى 'الفخر الكاذب والغرور' في هرم وعي هاوكينز؟",
          questionEn: "What is the primary underlying state behind intellectual vanity?",
          optionsAr: [
            "الشعور بالاستقرار الكامل والسيادة النقدية ومحبة الأخرين بالوقار والأكاديمية.",
            "الخوف الدقين والنقص الداخلي الذي يستتر تفاخرياً خلف الألقاب والمظاهر الكاذبة خشية انكشاف حقيقة ضعفه وبطلان فكره.",
            "الرغبة في توفير القروض المالية للبنوك للتخلص من نفقات الريع."
          ],
          optionsEn: [
            "Complete objective security, deep administrative poise, and authentic connection with peers.",
            "Deep-seated subconscious fear of inadequacy, which hides behind grandiose titles and credentials to evade verification and exposure.",
            "The urge to clear bank debts and bypass corporate interest payments."
          ],
          correctIndex: 1,
          explanationAr: "إخماد التعالي ينقلك لمستوى الشجاعة والاستقرار الصادق، مانحاً إياك وقاراً وثباناً مبرهناً مميزاً.",
          explanationEn: "Surrendering intellectual vanity elevates your system to Courage and Neutrality, anchoring your decisions on authentic poise and real influence."
        }
      ]
    },
    {
      id: 'lg_ch9',
      chapterNum: 9,
      titleAr: 'الفصل التاسع: الشجاعة والتمكين الذاتي وبوابة الابتكار الخارق',
      titleEn: 'Chapter 9: Ascending to Courage & Activating Conscious Empowerment',
      descriptionAr: 'صعود الوعي الإنساني فوق عتبة ٢٠٠ الإستراتيجية الفولاذية، استرداد الأمان الداخلي والمبادرة بحرية ويقين تم بغير حدود.',
      descriptionEn: 'Crossing the critical baseline of 200, anchoring unshakeable accountability, and activating advanced business initiative.',
      lessons: [
        {
          id: 'lg_ch9_l1',
          idNum: 1,
          titleAr: '1. شفرة ٢٠٠: النهر العظيم وقوة العبور بالملعب الموجه للأصول',
          titleEn: '1. The Pivot of 200: Transitioning from Force to Genuine Power',
          duration: '4m',
          type: 'intro',
          contentAr: `يمثل الوصول لـ **الشجاعة (Courage - ٢٠٠)** خط الدفاع المعياري الأكبر في الكيان الإنساني المعاصر； فهو عتبة التحول من مستويات الطاقة السلبية الهدامة إلى القوة البناءة والنزاهة الواعية الممتازة.
          
**استرداد المسؤولية واليقين والدفاع عن الذات:**
- عند ٢٠٠، يتوقف الفرد عن شكاوى التباكي ويوجه فكره وقوته نحو: "أنا المسؤول عن حياتي، وعن قراراتي، وعن أصولي وعقودي. سأتصرف بنبالة وشرف للدفاع عن مصيري". يهدأ القلق الفكري التافه وتتضح مسالك النهضة المعرفية بوقار متكامل.`,
          contentEn: `Crossing border **Level 200 (Courage)** serves as the ultimate energetic turning point. At this altitude, your system transitions from reactive victimhood into objective focus and authentic competence.
          
**Unconditional Accountability:**
- At level 200, you cease complaining and state: "I assume 100% responsibility for my performance and my financial assets. I decline to blame external factors. What is my logical action Now?" Chronic worry subdues and professional initiatives clear.`
        },
        {
          id: 'lg_ch9_l2',
          idNum: 2,
          titleAr: '2. تفعيل المبادرة الشجاعة: حرق التردد المترنح خلف الأوراق الخائبة',
          titleEn: '2. The Execution Blueprint: Neutralizing Stalling and Indecision',
          duration: '3m',
          type: 'core',
          contentAr: `لكي توسع مبادرتك اليوم، لا تنتظر توفر الضمانات والسكينة الفجائية الكاملة； بل اعترف بالتردد المترنح واسمح بالرحيل لشحنة الذعر المكبوثة.
          
**هندسة الاستقلالية الحيوية:**
- رصد الخوف من ارتكاب الأخطاء بالعمل وتجاوزه بثقة بالغة وموضوعية تامة مبرهنة.
- صمم خططاً فولاذية وعقوداً صلبة للدخول بصفقات إستراتيجية رائدة وتحد الأوراق الركيكة وصون مصير مشاريعك بدفاع شجاع مبرز.`,
          contentEn: `To activate professional initiative, do not wait for perfect corporate climate or effortless security. Identify somatic resistance and release your claim on catastrophic fantasies.
          
**Executing on Business Avenues:**
- Target your subconscious dread of making strategic mistakes and disarm it with poise.
- Draft solid business designs and secure high-value contracts. Assume calculated risks confidently, protecting your projects from cognitive drift or bureaucratic delays.`
        },
        {
          id: 'lg_ch9_l3',
          idNum: 3,
          titleAr: '3. ممارسات وتأمل الشرف والسيادة: تطبيقات بساحات العمل بنبالة وبشرف',
          titleEn: '3. Standard Tips: Poise and risk-taking under Pressure',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الممارسات لإرساء قواعد الشجاعة والتمكين والسيادة الكلية اليوم:
          
- **تطبيق \'التحقيق الفوري للشرف\':** في مواجهة قرار مهاري معقد أو زحام إداري مكثف اليوم، قل بثبات وقار: "أنا مكتمل بحضور روحي وبجدارة تمكيني، سأتصرف بشرف ونزاهة للفوز وحل العقد".
- **تأمل هالة الشجاعة لطرد الصغائر:** وجه وعيك لغمر جسدك المادي بحضور الشجاعة والقوة الأكاديمية وطرد كل هموم الشهرة والمظاهرات التافهة الفانية بالكامل.`,
          contentEn: `Cultivate advanced structural courage using these steps:
          
- **The Integrity Reset Protocol:** When facing a complex system issue or loud board meeting, say: "I remain complete inside my original intelligence. I choose to act with absolute transparency and objectivity."
- **The Courage Flooding Technique:** direct conscious energy to saturate your form with the vibration of Courage. This filters peripheral workspace politics and installs silent administrative dominance.`
        }
      ],
      quiz: [
        {
          questionAr: "ما هو التغير الجوهري المعرفي المصاحب لتردد مستوى 'الشجاعة (٢٠٠ - Courage)' في هرم وعي هاوكينز؟",
          questionEn: "What is the primary spiritual shift that occurs when reaching Level 200?",
          optionsAr: [
            "التخلي التام عن المبادرات والجلوس مع التبلد والفتور والهروب من سداد القروض والبنوك بوقاحة.",
            "تحمل كامل المسؤولية عن تفاصيل حياتك وأصولك وقراراتك، والتوقف الكامل عن الشكاوى والاعتراض العنيف، والتحرك بنزاهة موضوعية لحل المشكلات وكسب الفرص ببراعة.",
            "معاداة الزملاء وصناعة كتل إدارية لتقويض القيادات بشكل همجي."
          ],
          optionsEn: [
            "Fleeing all major assignments, adopting apathy, and evading fiscal duties with insolence.",
            "Assuming 100% accountability for your performance, actions, and assets, halting complaints, and acting with objectivity and high integrity to capture commercial successes.",
            "Sabotaging colleagues and forming corporate factions to destroy leadership teams."
          ],
          correctIndex: 1,
          explanationAr: "الشجاعة (٢٠٠) هي عتبة الحرية الكبرى، وانطلاقتك منها تحد عقد التباطؤ والتباكي وتقيم لك مملكاً فكرياً شاملاً.",
          explanationEn: "Courage (200) serves as the energetic fulcrum, anchoring your system on solid accountability and profound personal power."
        }
      ]
    },
    {
      id: 'lg_ch10',
      chapterNum: 10,
      titleAr: 'الفصل العاشر: بلوغ القبول والحب والسلام وثمرات التحرر الروحي الختامية',
      titleEn: 'Chapter 10: Reaching Acceptance, Love & Complete Peace: The Ultimate Fruits',
      descriptionAr: 'الاتحاد الكلي مع تيار الكينونة الساكنة بالباطن، الوحدة مع الجمال المعرفي اللامتناهي، والعلاج الكشفي التام لعلاقة الجسد والفكر بسلام وثبات مطلق.',
      descriptionEn: 'Aligning with the infinite flow of conscious Being, reconciling physical vitality with mental purity, and harvesting the ultimate fruits of total surrender.',
      lessons: [
        {
          id: 'lg_ch10_l1',
          idNum: 1,
          titleAr: '1. لغز القبول والحب والسلام الكوني: مستويات القوة الشامخة باذخة التميز',
          titleEn: '1. Reaching Love (500) & Peace (600): The Heights of Self-Actualization',
          duration: '4m',
          type: 'intro',
          contentAr: `عند صعود الوعي لمستويات **القبول (٣٥٠)**، ثم **الحب (٥٠٠ - Love)**، و**السلام (٦٠٠ - Peace)**، تتلاشى تماماً صراعات الأنا الكاذبة وتنهدم حواجز الانفصال والخصومة بالكلية.
          
**رؤية الجمال المعرفي اللامتناهي بساحة العمل:**
- ينظر العارف في هذه المستويات للأخرين والزملاء كشركاء في تيار الوجود ككل، ويسود ذهنه صفاء تام يقهر الصغائر ويعم أركان مملكته نوراً حضورياً جلاءً مميزاً، لتجتمع بين يديه مصالحه وأمواله وأصوله بسلام وسهولة فائقة باذخة الصدارة والوقار الصالح المبرهن.`,
          contentEn: `Ascending to **Acceptance (350)**, **Love (500)**, and **Peace (600)** entirely dissolves egoic friction and historical disputes.
          
**Poised Operational Awareness:**
- At these altitudes, you view colleagues and competitors as integral aspects of a unified operational fabric. Your mind resides in elegant, pristine clarity. Wealth, and intellectual assets organize themselves with immaculate precision around your serene presence.`
        },
        {
          id: 'lg_ch10_l2',
          idNum: 2,
          titleAr: '2. سيكولوجيا وعلاقة العقل والجسم: تطهير الخلايا وشفاء الأمراض بالباطن',
          titleEn: '2. Mind-Body Resonances: Reboots through Emotional Purity',
          duration: '3m',
          type: 'core',
          contentAr: `يقسم هاوكينز وبكار أن المرض الجسدي ما هو إلا تجسيد وتكثيف مادي لتوترات ومشاعر مكبوثة مكبوسة بالبدن والوعاء لسنوات طويلة.
          
**الشفاء واسترداد الحيوية والمناعة:**
- بفضل السماح المستمر بالرحيل، ينفك الاحتقان العصبي المترسب بالخلايا والشرايين، وترتد دماء المناعة تفيض صحة وصيانة وعافية تامة، ليقترن نضج فكرك الساكن الروح بصحة بدنك الشهم المحتسب الصابر لتنعم بجنان الوفرة والوقار والابتكار بأمان تام.`,
          contentEn: `Dr. Hawkins establishes that physical symptoms are somatic projections of historically suppressed anxiety and resentment in major cellular pathways.
          
**Rejuvenating the Container:**
- By practicing consistent release, the nervous grid of your physical body decompresses. Healing currents restore vigor and immunologic integrity, combining clean physical health with unshakeable cognitive poise to generate advanced creativity and deep administrative status.`
        },
        {
          id: 'lg_ch10_l3',
          idNum: 3,
          titleAr: '3. ثمار السماح بالرحيل الختامية وعقدة السلام الصالح',
          titleEn: '3. Standard Tips: Releasing all Locks and Reclaiming Pure Freedom',
          duration: '3m',
          type: 'tips',
          contentAr: `إليك هذه الوصفة الإلزامية لقطع دابر كل سجون الأنا وتثبيت عقد التحرر الختامي اليوم:
          
- **تطبيق \'الاستسلام الكلي المطلق للآن\':** قبل ختام لقائنا الإرشادى، استسلم لحقيقة الحضور بكامل كينونتك وجسد وعيك بالسلام الشامل； تحرر من رغبة السيطرة ودع تيار الحياة يسير ويرحب بخلودك بنجاح وسهولة تامين.
- **تأمل السكينة الكبرى لتصنيف الأمان:** اغمض عينيك، تنفس بنقاء، وافسح المجال لروائح السعادة والمدد المعرفي الكوني لينهمر ويطهر روحك بالكامل.`,
          contentEn: `Inject the ultimate baseline of conscious freedom using these keys today:
          
- **The Absolute Surrender to the Present:** Relinquish the frantic desire to manipulate or predict conditions. Yield entirely to the present moment, allowing your original intelligence to flow with pristine, unblocked vigor.
- **The Ultimate Peace Alignment:** Sit quietly, breathe slowly, and observe the vast, unshakeable backdrop of Stillness behind all temporal workspace events. This is your anchor of pure, eternal freedom.`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يفيدنا السماح بالرحيل وبلوغ مستويات القبول والسلام في علاج علاقة العقل والجسم؟",
          questionEn: "How does surrender and reaching Peace (600) support our mind-body wellness?",
          optionsAr: [
            "يؤدي لتخدير الخلايا ووجوب مراجعة البنوك والتهرب من سداد مستحقات المشاريع بوقاحة.",
            "يفك التشنجات العصبية المتكثفة بالخلايا والناتجة عن كبت المشاعر لسنوات، مما يرفع المناعة ويعزز حيوية البدن ويقرن السلام الداخلي بصحة البدن الشهم لتسود وتنجز بسلام وقار.",
            "يجعلك تعادي الجميع وتعتزل الأسواق العالمية لتعيش في الكهوف مهزوماً."
          ],
          optionsEn: [
            "It drugs the cells and prompts you to avoid physical banks and skip strategic financial duties with insolence.",
            "It decompresses historical somatic holdings, dramatically elevating immunological response and returning your physical vessel to absolute vigor and executive capacity.",
            "It prompts you to retire from global labor, and dwell inside mountain caves forever."
          ],
          correctIndex: 1,
          explanationAr: "الاتصال بكينونتك الواسعة ودفء السلام يجدد حيوية البدن ويفرض وقار الحضور وصدارة النجاح بغير شروط بالكلية.",
          explanationEn: "Aligning your biology with deep resilience, securing uncompromised creative authority and profound professional influence."
        }
      ]
    },
    {
      id: 'lg_ch11',
      chapterNum: 11,
      titleAr: 'الفصل الحادي عشر: تحويل العلاقات والروابط الإنسانية - من التملك والتعلق إلى التمكين والنبل المتبادل',
      titleEn: 'Chapter 11: Transforming Relationships - Releasing Attachment & Embracing Radical Support',
      descriptionAr: 'قالت فك رموز التعلق والاضطرابات العاطفية في بيئات العمل والشراكة وكيفية الانتقال لساحة التقدير والتآزر الطاهر.',
      descriptionEn: 'The psychology of expectations and professional attachments, and how surrendering control transforms working relationships into fountains of synergy.',
      lessons: [
        {
          id: 'lg_ch11_l1',
          idNum: 1,
          titleAr: '1. لجام التعلق والتملك: تحرير الرغبة في السيطرة وتغيير الآخرين',
          titleEn: '1. The Trap of Possession: Releasing the Need to Control or Reform Others',
          duration: '4m',
          type: 'core',
          contentAr: `يتولد أعظم قدر من العذاب في العلاقات الإنسانية والشراكات المهنية من "التعلق المرضي والرغبة في السيطرة وتعديل وتغيير سلوكيات الآخرين". عندما تطلق العنان للسماح برحيل تلك الرغبة العنيفة وتقبل الزملاء والشركاء كما هم بكافة جوانبهم، تتبخر مشاعر الضغينة والغضب وتفسح المجال لتعاون مبدع وثقة مهنية فائقة تعود بالخير العميم للجميع.`,
          contentEn: `The peak of emotional friction within corporate alliances arises from attachments and the exhausting desire to manipulate or reconstruct other personalities. Surrendering your need to manage others liberates your attention, creating fertile ground for authentic collaboration and trust.`
        },
        {
          id: 'lg_ch11_l2',
          idNum: 2,
          titleAr: '2. التعاطف المطلق والوفاق الطاهر: كيف تقرن الحدود القوية بالسلام والمحبة؟',
          titleEn: '2. Dynamic Interstellar Support: Pairing Resolute Boundaries with Poise and Honor',
          duration: '3m',
          type: 'tips',
          contentAr: `السماح بالرحيل لا يعني الوهن أو قبول الظلم والضياع؛ بل يمكنك دائماً وبكل نبل وضع حدود معاملاتية بالغة الدقة والقوة في العمل ولكن بقلب محب وصافٍ خالٍ من الحقد والغضب والتوتر العاطفي. هذا المستودع من التوازن يمنع استنزاف جهازك العصبي ويضمن اتخاذ قراراتك بروح السكينة والشرف والوقار الصامت.`,
          contentEn: `Surrender is not passive victimhood. True character enables you to enforce strong, clear boundary lines in your company while maintaining a mind fully decoupled from malice and anger. This pristine emotional neutrality preserves your physiological energy and highlights your authority.`
        }
      ],
      quiz: [
        {
          questionAr: "كيف يؤثر تطبيق آلية 'السماح بالرحيل' للتعلق ورغبة السيطرة على العلاقات وصحة بيئة العمل؟",
          questionEn: "How does releasing your attachment and core need to control others impact professional relationships?",
          optionsAr: [
            "يؤدي للخصومة الدائمة ومقاطعة الزملاء وتأخير تسليم الأكواد والمنتجات.",
            "يبدد التشنج ومشاعر الضغينة والتوتر الغاضب، مما يرسي مناخاً طاهراً من الثقة والقبول والتعاون النبيل المتبادل بوقار وصدارة.",
            "يجعل الجميع يمارسون الكسل ويتوقفون عن متابعة الميزانية بالكامل."
          ],
          optionsEn: [
            "It generates endless personal vendettas and delays the shipment of project codebases.",
            "It neutralizes core interpersonal friction and active resentments, replacing them with trust, absolute acceptance, and synergistic partnership in workspace environments.",
            "It dictates that all coworkers adopt total laziness and suspend corporate budget analysis."
          ],
          correctIndex: 1,
          explanationAr: "إطلاق مشاعر السيطرة يحميك من صراعات الأنا المجهدة ويؤهلك للصدارة والوفاق كمنارة إدارية ونفسية ملهمة بساحات النجاح.",
          explanationEn: "Relinquishing control over peers protects you from draining ego matches, securing your reputation as an advanced, highly integrated leader."
        }
      ]
    },
    {
      id: 'lg_ch12',
      chapterNum: 12,
      titleAr: 'الفصل الثاني عشر: الكيمياء المهنية والذاتية الخارقة للتحرر - التدفق المعرفي وصناعة المعجزات بسلام داخلي بوقار',
      titleEn: 'Chapter 12: Spiritual & Strategic Transcendence - The Practical Alchemy of Living in Pure Flow',
      descriptionAr: 'تحقيق أعلى مستويات كفاءة الإنجاز والتراكم المعرفي عبر التناغم المطلق مع الكينونة وتحرير عقد التوقعات السلبية بوقار تام وشرف.',
      descriptionEn: 'Achieving peak productivity, business clarity, and creative breakthroughs by alignment with the Unmanifest and freeing yourself from mental expectations.',
      lessons: [
        {
          id: 'lg_ch12_l1',
          idNum: 1,
          titleAr: '1. تحرير التوقعات والاعتصام بالبداهة والذكاء الكوني: التدفق كأداة تشغيلية فريدة',
          titleEn: '1. Dropping Expectations: Transitioning from Anxious Forcing to Dynamic Creative Flow',
          duration: '4m',
          type: 'core',
          contentAr: `أكبر معوق للابتكار بساحة العمل هو التخوف الدائم والتعلق بالنتائج والتوقعات المكبلة. عندما تقوم بالسماح ببرحيل تلك الآمال اللحظية المشوبة بالذعر وتركز بكل ذرة من كينونتك على الاتقان والصدق الفعلي في عملك، تتدفق إليك الأفكار الابتكارية النادرة وتتحطم كل قيود المحدوديات، لتقترن أصولك بصدارة باذخة ونجاح دائم مبروك ونبل متجذر بضميرك.`,
          contentEn: `The peak bottleneck to advanced creativity is corporate attachment to short-term numbers and expectations. By surrendering the fear of outcome and focusing purely on the absolute craftsmanship of your craft, brilliant solutions manifest effortlessly.`
        },
        {
          id: 'lg_ch12_l2',
          idNum: 2,
          titleAr: '2. الرياضة اليومية للتحرر في ختام السفر: بروتوكول الصيانة الروحية المستدامة',
          titleEn: '2. The Perpetual Re-centering: Protocol of Continuous Daily Decompression',
          duration: '3m',
          type: 'tips',
          contentAr: `في منتهى كفاحنا الفلسفي المبارك للتطوير الذاتي؛ احمِ عقلك وروحك بممارسة التحرير المستمر والتطهير للرواسب العاطفية بانتظام. لا تكبت غضباً، ولا تكتم كبرياءً زائراً؛ بل اسمح لكل سحابة أن تمر، حافظ على وقارك الشهم وصيت كرامتك الشامخ، وكن سفيراً حياً للسلام والمعرفة ومحبة الخير لجميع البريات. تقدم الآن مستبشراً؛ فأنت حقاً وصدقاً مستعد دائماً للسيادة والوفاق!`,
          contentEn: `As you conclude this transcendent curriculum, commit to consistent daily decompression of any negative remnants. Repress nothing; allow all mental storms to pass. Cultivate unyielding character and profound personal authority, serving as a beacon of wisdom and serene contribution. Step forward with uncompromised faith and claim your success!`
        }
      ],
      quiz: [
        {
          questionAr: "ما هو المنتهى المعرفي والروحي المبارك لتطبيق عقود 'السماح بالرحيل' بشكل شامل ومستدام في حياتك؟",
          questionEn: "What is the ultimate, life-altering outcome of applying continuous daily surrender in your journey?",
          optionsAr: [
            "الوقوع في دركات العجز والانسحاب التام من دراسات الإدارة والحسابات الصالحة.",
            "الوصول للسيادة العاطفية والمعرفية التامة وعيش حالة التدفق وتحقيق صروح الأصول الموفورة والأعمال بنبل وشرف ووقار طاهر وبأعلى كفاءة وسلام.",
            "تراكم الديون وتجنب دفع الحقوق وتضييع الصلوات والمواعيد بالأكاديمية."
          ],
          optionsEn: [
            "Sliding into helplessness and completely halting study in finance and structured management.",
            "Attaining complete emotional sovereignty, experiencing absolute functional flow, and building durable commercial assets with unyielding ethics, peace, and ultimate distinction.",
            "Accumulating debt, violating client contracts, and missing project delivery milestones."
          ],
          correctIndex: 1,
          explanationAr: "تطهير وعاء الروح باستمرار يفجر كوامن الإبداع واليقين ويزين حضورك بصيغة ريادية فريدة ونبيلة يرجى خيرها دوماً بوقار وسلام.",
          explanationEn: "Purifying your inner container unlocks your ultimate creative intelligence, framing your brand as a noble and powerful leader of eternal value."
        }
      ]
    }
  ]
};
