import React, { useState } from 'react';
import { Sparkles, Video, Film, Wand2, BookOpen, AlertCircle, CheckCircle2, ChevronRight, Layers, Award } from 'lucide-react';
import { motion } from 'motion/react';
import { ProducedVideoLesson } from '../data/producedVideoLessons';

interface AiVideoStudioModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLessonCreated: (lesson: ProducedVideoLesson) => void;
  isRtl?: boolean;
}

const PRESET_TOPICS = [
  { topicEn: 'Hospital & Doctor Consultation', topicAr: 'استشارة الطبيب والمستشفى بالإنجليزية', level: 'A2', badge: 'صحة وحياة 🏥' },
  { topicEn: 'Hotel Booking & Luxury Check-in', topicAr: 'حجز الفنادق وتسجيل الوصول الفاخر', level: 'B1', badge: 'سياحة وفنادق 🏨' },
  { topicEn: 'Job Salary Negotiation & Perks', topicAr: 'التفاوض على الراتب والمزايا الوظيفية', level: 'B2', badge: 'مهني وبيزنس 💼' },
  { topicEn: 'Ordering Food in Italian Restaurant', topicAr: 'طلب الطعام في مطعم إيطالي شهير', level: 'A1', badge: 'مطاعم وطعام 🍕' },
  { topicEn: 'Artificial Intelligence & Smart Automation', topicAr: 'الذكاء الاصطناعي والأتمتة الرقمية', level: 'C1', badge: 'تكنولوجيا متقدمة 🤖' },
  { topicEn: 'Kids Phonics: Colors, Numbers & Animals', topicAr: 'أصوات الحروف، الألوان والأرقام للأطفال', level: 'A1', badge: 'أطفال ومرح 🎈' }
];

export const AiVideoStudioModal: React.FC<AiVideoStudioModalProps> = ({
  isOpen,
  onClose,
  onLessonCreated,
  isRtl = true
}) => {
  const [customTopic, setCustomTopic] = useState('');
  const [selectedLevel, setSelectedLevel] = useState('A2');
  const [selectedAudience, setSelectedAudience] = useState('general');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStep, setGenerationStep] = useState('');
  const [errorText, setErrorText] = useState('');

  if (!isOpen) return null;

  const handleGenerate = async (topicToUse?: string, levelToUse?: string) => {
    const finalTopic = (topicToUse || customTopic).trim();
    const finalLevel = levelToUse || selectedLevel;

    if (!finalTopic) {
      setErrorText(isRtl ? 'الرجاء كتابة عنوان أو موضوع الدرس المرئي.' : 'Please enter a video lesson topic.');
      return;
    }

    setIsGenerating(true);
    setErrorText('');
    setGenerationStep(isRtl ? '1/3: صياغة سيناريو المشاهد التفاعلية...' : '1/3: Scripting interactive scenes...');

    try {
      setTimeout(() => {
        setGenerationStep(isRtl ? '2/3: توزيع الشخصيات والترجمة وضبط مخارج الحروف...' : '2/3: Directing characters, phonetics & subtitles...');
      }, 1500);

      setTimeout(() => {
        setGenerationStep(isRtl ? '3/3: بناء نقاط التقييم والاختبار التفاعلي...' : '3/3: Assembling checkpoints & vocabulary flashcards...');
      }, 3000);

      const resp = await fetch('/api/videos/generate-lesson-video', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: finalTopic,
          level: finalLevel,
          targetAudience: selectedAudience,
          lang: isRtl ? 'ar' : 'en'
        })
      });

      if (!resp.ok) {
        throw new Error(`Server responded with ${resp.status}`);
      }

      const data = await resp.json();
      
      const newLesson: ProducedVideoLesson = {
        id: `ai-vid-${Date.now()}`,
        titleEn: data.titleEn || `Mastering ${finalTopic}`,
        titleAr: data.titleAr || `إتقان ${finalTopic}`,
        category: 'conversation',
        level: (data.level || finalLevel) as any,
        duration: data.estimatedDuration || '4:15',
        thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop',
        badge: 'إنتاج الذكاء الاصطناعي 🪄',
        summaryEn: data.summaryEn || `An interactive audiovisual video lesson generated by AI.`,
        summaryAr: data.summaryAr || `درس مرئي بالصوت والصورة تم إنتاجه بواسطة الذكاء الاصطناعي للأكاديمية.`,
        scenes: data.scenes || [],
        vocabulary: data.vocabulary || []
      };

      setIsGenerating(false);
      onLessonCreated(newLesson);
      onClose();

    } catch (err: any) {
      console.warn("Generation error:", err);
      setIsGenerating(false);
      setErrorText(isRtl ? 'حدث خطأ أثناء الاتصال بنموذج الذكاء الاصطناعي، يرجى المحاولة مرة أخرى.' : 'Error generating video lesson, please retry.');
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-950/75 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className={`bg-white rounded-[2.5rem] p-6 sm:p-8 max-w-2xl w-full border-4 border-slate-200 shadow-2xl relative max-h-[90vh] overflow-y-auto ${
          isRtl ? 'font-arabic' : 'font-sans'
        }`}
        dir={isRtl ? 'rtl' : 'ltr'}
      >
        {/* Header */}
        <div className="flex items-center justify-between pb-4 mb-6 border-b-2 border-slate-100">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 bg-gradient-to-tr from-[#58cc02] to-[#1cb0f6] text-white rounded-2xl flex items-center justify-center shadow-md">
              <Wand2 size={24} />
            </div>
            <div>
              <h3 className="font-black text-slate-800 text-lg sm:text-xl">
                {isRtl ? 'استوديو إنتاج الدروس بالصوت والصورة 🎬🪄' : 'AI Audiovisual Video Producer Studio'}
              </h3>
              <p className="text-slate-400 text-xs font-bold">
                {isRtl ? 'أنتج درساً مرئياً تفاعلياً ناطقاً بالصوت والصورة والشخصيات لأي موضوع لغوي بضغطة زر' : 'Produce a full narrated educational video with character animations in seconds'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isGenerating}
            className="w-8 h-8 rounded-full bg-slate-100 text-slate-400 hover:text-slate-600 flex items-center justify-center font-bold"
          >
            ✕
          </button>
        </div>

        {isGenerating ? (
          <div className="py-14 text-center space-y-4">
            <div className="w-16 h-16 border-4 border-[#58cc02] border-t-transparent rounded-full animate-spin mx-auto" />
            <h4 className="text-base font-black text-slate-800">
              {isRtl ? 'جاري إخراج وتوليد الدرس المرئي بالكامل...' : 'Directing and rendering audiovisual lesson...'}
            </h4>
            <p className="text-xs font-bold text-[#58cc02] bg-[#58cc02]/10 py-1.5 px-4 rounded-full inline-block animate-pulse">
              {generationStep}
            </p>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Custom Topic Input */}
            <div>
              <label className="block text-xs font-black text-slate-500 uppercase tracking-wider mb-2">
                {isRtl ? 'موضوع أو سياق الدرس المطلوب إنتاجه ✍️' : 'Lesson Topic or Real-Life Context'}
              </label>
              <div className="relative">
                <input
                  type="text"
                  value={customTopic}
                  onChange={(e) => setCustomTopic(e.target.value)}
                  placeholder={isRtl ? 'مثال: محادثة شراء ملابس في متجر لندني، مقابلة عمل مهندس برمجيات...' : 'e.g. Booking a luxury train ticket, Job interview at a tech startup...'}
                  className="w-full text-xs sm:text-sm font-bold border-2 border-slate-200 focus:border-[#58cc02] outline-none rounded-2xl p-4 transition-colors"
                />
              </div>
            </div>

            {/* Level Selector */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-black text-slate-500 uppercase tracking-wider mb-2">
                  {isRtl ? 'المستوى المستهدف (CEFR)' : 'Target Level'}
                </label>
                <div className="grid grid-cols-6 gap-1 bg-slate-100 p-1.5 rounded-xl">
                  {['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].map((lvl) => (
                    <button
                      key={lvl}
                      type="button"
                      onClick={() => setSelectedLevel(lvl)}
                      className={`py-1.5 font-black text-xs rounded-lg transition-all ${
                        selectedLevel === lvl
                          ? 'bg-[#58cc02] text-white shadow-sm'
                          : 'text-slate-500 hover:text-slate-800'
                      }`}
                    >
                      {lvl}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="block text-xs font-black text-slate-500 uppercase tracking-wider mb-2">
                  {isRtl ? 'الفئة العمرية / الجمهور' : 'Target Audience'}
                </label>
                <div className="grid grid-cols-3 gap-1 bg-slate-100 p-1.5 rounded-xl text-xs font-bold">
                  <button
                    type="button"
                    onClick={() => setSelectedAudience('general')}
                    className={`py-1.5 rounded-lg transition-all ${
                      selectedAudience === 'general' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'
                    }`}
                  >
                    {isRtl ? 'عام' : 'General'}
                  </button>
                  <button
                    type="button"
                    onClick={() => setSelectedAudience('business')}
                    className={`py-1.5 rounded-lg transition-all ${
                      selectedAudience === 'business' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'
                    }`}
                  >
                    {isRtl ? 'مهني' : 'Business'}
                  </button>
                  <button
                    type="button"
                    onClick={() => setSelectedAudience('kids')}
                    className={`py-1.5 rounded-lg transition-all ${
                      selectedAudience === 'kids' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500'
                    }`}
                  >
                    {isRtl ? 'أطفال' : 'Kids'}
                  </button>
                </div>
              </div>
            </div>

            {/* Ready Preset Topics Suggestions */}
            <div>
              <label className="block text-xs font-black text-slate-500 uppercase tracking-wider mb-2">
                {isRtl ? 'أو اختر من المواضيع الجاهزة المقترحة 💡' : 'Or Pick Suggested Popular Scenario'}
              </label>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {PRESET_TOPICS.map((preset, pIdx) => (
                  <button
                    key={`preset-${pIdx}`}
                    onClick={() => {
                      setCustomTopic(preset.topicEn);
                      setSelectedLevel(preset.level);
                    }}
                    className={`p-3 text-left rounded-xl border-2 transition-all flex items-center justify-between gap-2 ${
                      customTopic === preset.topicEn
                        ? 'bg-[#58cc02]/10 border-[#58cc02] text-[#46a302]'
                        : 'bg-slate-50 border-slate-200/70 hover:bg-slate-100 text-slate-700'
                    }`}
                  >
                    <div>
                      <span className="block font-black text-xs">{isRtl ? preset.topicAr : preset.topicEn}</span>
                      <span className="text-[10px] text-slate-400 font-bold">{preset.badge} • Level {preset.level}</span>
                    </div>
                    <ChevronRight size={14} className={isRtl ? 'rotate-180' : ''} />
                  </button>
                ))}
              </div>
            </div>

            {errorText && (
              <div className="p-3 bg-rose-50 border border-rose-200 text-rose-600 rounded-xl text-xs font-bold flex items-center gap-2">
                <AlertCircle size={16} />
                <span>{errorText}</span>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex items-center justify-end gap-3 pt-4 border-t-2 border-slate-100">
              <button
                type="button"
                onClick={onClose}
                className="px-5 py-3 text-slate-500 hover:text-slate-800 text-xs font-black uppercase"
              >
                {isRtl ? 'إلغاء' : 'Cancel'}
              </button>
              <button
                type="button"
                onClick={() => handleGenerate()}
                className="px-6 py-3.5 bg-[#58cc02] hover:bg-[#68ee04] text-white font-black text-xs uppercase tracking-wider rounded-2xl border-b-4 border-[#3e9202] active:scale-95 transition-all flex items-center gap-2 shadow-lg shadow-[#58cc02]/30"
              >
                <Sparkles size={16} />
                <span>{isRtl ? 'إنتاج الدرس المرئي الآن 🚀' : 'Produce Lesson Now 🚀'}</span>
              </button>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
};
